# Jekyll configuration
title: Đạp xe xuyên Việt
description: Đi để đi
baseurl: ""
remote_theme: just-the-docs/just-the-docs
url: https://dapxexuyenviet.github.io
language: vi
author:
  name: Đạp xe xuyên Việt
  email: dapxexuyenviet@xuvi.vn
  url: https://dapxexuyenviet.github.io

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/avatar-kuzan.png"
# Aux links for the upper right navigation
aux_links:
  "Đạp xe xuyên Việt on GitHub":
    - "//github.com/dapxexuyenviet.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
